NumPy


In [3]:
import numpy as np
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
L = range(1000)
%timeit [i**2 for i in L]

299 µs ± 6.24 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
a = np.arange(1000)
%timeit a**2

1.46 µs ± 334 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [29]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a
a.ndim
a.shape
# len(a)

(1, 3, 3)

In [ ]:
# 1D array is called a vector
# 2d array is called a matrix
# nd array are called Tensor

In [34]:
# gives equal no. of points , including start and end
a = np.linspace(0,10,6)
a

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [39]:
a = np.ones((3,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [48]:
a = np.diag([1,2,3,4,5])
a


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [47]:
np.diag(a)

array([1, 2, 3, 4, 5])

In [50]:
a = np.random.rand(5)
a

array([0.63116292, 0.27506923, 0.35894754, 0.95396272, 0.40580114])

In [53]:
a = np.random.randn(5)
a

array([ 0.41863877, -0.87244452, -0.14762237, -1.18898005,  0.8749801 ])

In [52]:
a = np.arange(10)
a.dtype

dtype('int64')

In [55]:
a = np.arange(10,dtype='float')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [57]:
a = np.arange(10)
print(a[5])

5


In [64]:
a = np.diag([1,2,3])
print(a[2,2])
a[2,2] = 4. #can assign value
print(a[2,2])

3
4


In [81]:
b = np.arange(10)
b[1:8:2]


array([1, 3, 5, 7])

In [83]:
b = np.arange(10)
b[5:7] = 10
b

array([ 0,  1,  2,  3,  4, 10, 10,  7,  8,  9])

In [99]:
d = np.arange(5)
c = d[::-1]

c

array([4, 3, 2, 1, 0])

In [107]:
a = np.random.randint(0,20,16)
mask = a % 2 == 0
a_even = a[mask]
a
a_even

array([16,  4, 10, 18, 12, 10,  4, 16, 12,  2])