In [5]:
import numpy as np

In [7]:
a = np.arange(5)
a+1

array([1, 2, 3, 4, 5])

In [8]:
a**2

array([ 0,  1,  4,  9, 16])

In [12]:
b = np.ones(5)+1
a-b

array([-2., -1.,  0.,  1.,  2.])

In [13]:
a*b

array([0., 2., 4., 6., 8.])

In [18]:
c = np.diag([1,2,3,4])
print(c * c)
print("*******************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*******************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [20]:
a = np.array([1,2,3,4])
b = np.array([1,6,8,4])
a < b

array([False,  True,  True, False])

In [21]:
a = np.array([1,2,3,4])
b = np.array([1,6,8,4])
np.array_equal(a,b)

False

In [22]:
a =np.arange(10)
np.sum(a)

45

In [27]:
x = np.array([[1,1],[2,2]])
np.sum(x)


6

In [84]:
# columns (first dimension)
x = np.array([[1,1],[2,2]])
x.sum(axis = 0)
x

array([[1, 1],
       [2, 2]])

In [83]:
# rows (second dimention)
x = np.array([[1,1],[2,2]])
x.sum(axis = 1)
x

array([[1, 1],
       [2, 2]])

In [40]:
a = np.random.rand(6)
a.min()

0.11291396044293267

In [39]:
a = np.random.randint(0,20,6)
a.max()

17

In [46]:
# gives the index of maximum element
a = np.arange(0,16,2)
a.argmax()

7

In [47]:
np.all([True,False,False])

False

In [48]:
np.any([True,False,False])

True

In [51]:
a =np.diag([1,2,3,4,5])
np.any(a != 0)

True

In [52]:
a =np.diag([1,2,3,4,5])
np.all(a != 0)

False

In [69]:
a =np.array([0,19,8])
np.median(a)

8.0

In [71]:
a = range(11)
even = list(filter(lambda a : a%2 == 0 , a))
print(even)

[0, 2, 4, 6, 8, 10]


In [9]:
a = range(11)
sq = list(map(lambda a : a**3, a))
print(sq)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
import numpy as np
a = (np.arange(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print("##################")
a = a.T
print(a)
print("##################")
a = a + np.array([0,1,2])
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
##################
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
##################
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [27]:
a = np.arange(0,40,10)
a = a[:, np.newaxis] #converts 1d into 2d array
print(a)
print("*************************")
a = a + np.array([0,1,2])
print(a)


[[ 0]
 [10]
 [20]
 [30]]
*************************
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [35]:
a = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
a = a.ravel() # converts tensors into vectors
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
a.ravel()
print(a)
a.T
print(a)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [45]:
b = a.ravel()
print(b)
b = b.reshape(3,3) #used to convert 1d into 2d
b

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
a = np.arange(2,4)
a
# b = np.sort(a,axis = 1)
# b

array([2, 3])

In [60]:
a = np.array([4,3,1,2])
j = np.argsort(a)
j
a[j]

array([1, 2, 3, 4])